services:
  - type: web
    name: bitb-violation-checker
    env: node
    region: singapore 
    plan: free 
    branch: master
    buildCommand: npm install && npm run build
    startCommand: npm run start:prod
    envVars:
      GEMINI_API_KEY:
        fromSecret: AIzaSyALznhuNANOhS_ChqxswWbRyCV2OHk5F30 
      NODE_ENV: production